name: tictactoe_package
description: Tic-Tac-Toe Game Widget for Flutter
version: 0.0.1
author: Yakup Murat CAYLAK<y.muratcaylak@gmail.com>
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  bloc: ^4.0.0
  flutter_bloc: ^4.0.1
  equatable: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  #